### ISSUE TITLE
French datasets

### ISSUE THREAD

**Issue by haubourg** [ai4up/eubucco#4]
Hi there. Very nice work !

I wanted to draw to your attention the French Building database I work on with my team.

https://www.data.gouv.fr/fr/datasets/base-de-donnees-nationale-des-batiments/

It is based on the BDTopo but footprints are redefined using tax and cadastral parcels informations. The we enrich the datasets with additional information like energy diagnosis for instance.  

All the best.

**Comment by milojevicdupontnikola** [comment]
Thank you Régis! I have started looking into your data, it looks great and would be happy to chat about it in the near future. Will reach out soon!

**Comment by haubourg** [comment]
With pleasure. A new version with comes every few months. Next one will identify a lot more complex buildings. Previous versions discarded footprint that were inconsistent with tax informations.
