### ISSUE TITLE
Where is it "input−dataset−metatable−v0.1.xlsx" file

### ISSUE THREAD

**Issue by aborruso** [ai4up/eubucco#5]
Hi,
first of all thank you for this project.

I would like to read about some metadata, but I do not find the file `input−dataset−metatable−v0.1.xlsx`.

Where is it?

Thank you

**Comment by andredaa** [comment]
Hello! 
I just wanted to open the same issue :))
Trying to find out which dataset you guys exactly used for Hamburg. 
Best Regards
Andre

**Comment by FlorianNachtigall** [comment]
Hi @aborruso and @andredaa,

You can find the `input−dataset−metatable−v0.1.xlsx` file at https://eubucco.com/data/ in the `Additional Files` section.

**Comment by aborruso** [comment]
Thank you
